package com.garfiec.librechat.core.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val LightBackground = Color(0xFFFFFFFF)
val LightOnBackground = Color(0xFF212121)
val LightSurface = Color(0xFFFFFFFF)
val LightSurfaceContainer = Color(0xFFF7F7F8)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF0F0F0)
val LightSurfaceContainerHigh = Color(0xFFF5F5F5)
val LightSurfaceContainerHighest = Color(0xFFEFEFEF)
val LightSecondaryContainer = Color(0xFFE3E3E3)
val LightSurfaceVariant = Color(0xFFE3E3E3)
val LightOnSurfaceVariant = Color(0xFF666666)
val LightOutline = Color(0xFF999999)
val LightOutlineVariant = Color(0xFFE0E0E0)
val LightPrimary = Color(0xFF8B5CF6)
val LightPrimaryContainer = Color(0xFF7C3AED)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightOnPrimaryContainer = Color(0xFFFFFFFF)
val LightError = Color(0xFFEF4444)
val LightOnError = Color(0xFFFFFFFF)

// Dark Theme Colors
val DarkBackground = Color(0xFF0D0D0D)
val DarkOnBackground = Color(0xFFECECF1)
val DarkSurface = Color(0xFF171717)
val DarkSurfaceContainer = Color(0xFF1A1A1A)
val DarkSurfaceContainerLowest = Color(0xFF0D0D0D)
val DarkSurfaceContainerLow = Color(0xFF171717)
val DarkSurfaceContainerHigh = Color(0xFF1E1E1E)
val DarkSurfaceContainerHighest = Color(0xFF252525)
val DarkSecondaryContainer = Color(0xFF2A2A2A)
val DarkSurfaceVariant = Color(0xFF424242)
val DarkOnSurfaceVariant = Color(0xFFAAAAAA)
val DarkOutline = Color(0xFF888888)
val DarkOutlineVariant = Color(0xFF333333)
val DarkPrimary = Color(0xFFAB68FF)
val DarkPrimaryContainer = Color(0xFFC084FC)
val DarkOnPrimary = Color(0xFF0D0D0D)
val DarkOnPrimaryContainer = Color(0xFF1A0040)
val DarkError = Color(0xFFEF4444)
val DarkOnError = Color(0xFFFFFFFF)
